const dependencies = {
  "@graphql-modules/core": "0.7.12",
  "apollo-cache-inmemory": "1.5.1",
  "apollo-client": "2.6.8",
  "apollo-link-batch-http": "1.2.3",
  "apollo-link-error": "1.1.10",
  "apollo-link-schema": "1.2.0",
  "apollo-link-ws": "1.0.17",
  "apollo-server-express": "2.4.8",
  "babel-polyfill": "6.26.0",
  "config": "3.2.2",
  "core-js": "3.6.4",
  "commander": "4.1.1",
  "express": "4.17.1",
  "express-session": "1.16.2",
  "graphql": "14.0.2",
  "graphql-tools": "4.0.0",
  "isomorphic-fetch": "2.2.1",
  "isomorphic-style-loader": "5.1.0",
  "react": "16.9.0",
  "react-apollo": "3.1.3",
  "react-dom": "16.9.0",
  "react-helmet-async": "1.0.3",
  "react-router-dom": "5.1.0",
  "reflect-metadata": "0.1.13",
  "serve-favicon": "2.5.0",
  "lodash": "4.17.15",
  "apollo-datasource-rest": "0.6.11"
};

const devDependencies = {
  "@babel/cli": "7.6.2",
  "@babel/core": "7.6.2",
  "@babel/plugin-transform-regenerator": "7.8.7",
  "@babel/plugin-proposal-class-properties": "7.5.5",
  "@babel/plugin-proposal-decorators": "7.6.0",
  "@babel/plugin-proposal-do-expressions": "7.6.0",
  "@babel/plugin-proposal-export-default-from": "7.5.2",
  "@babel/plugin-proposal-export-namespace-from": "7.5.2",
  "@babel/plugin-proposal-function-bind": "7.2.0",
  "@babel/plugin-proposal-function-sent": "7.5.0",
  "@babel/plugin-proposal-json-strings": "7.2.0",
  "@babel/plugin-proposal-logical-assignment-operators": "7.2.0",
  "@babel/plugin-proposal-nullish-coalescing-operator": "7.4.4",
  "@babel/plugin-proposal-numeric-separator": "7.2.0",
  "@babel/plugin-proposal-optional-chaining": "7.6.0",
  "@babel/plugin-proposal-pipeline-operator": "7.5.0",
  "@babel/plugin-proposal-throw-expressions": "7.2.0",
  "@babel/plugin-syntax-dynamic-import": "7.2.0",
  "@babel/plugin-syntax-import-meta": "7.2.0",
  "@babel/preset-env": "7.6.2",
  "@babel/preset-flow": "7.0.0",
  "@babel/preset-react": "7.0.0",
  "@babel/preset-stage-0": "7.0.0",
  "babel-loader": "8.0.6",
  "babel-plugin-dynamic-import-node": "2.3.0",
  "babel-plugin-module-resolver": "3.2.0",
  "babel-plugin-transform-require-ignore": "0.1.1",
  "css-loader": "3.2.0",
  "flow-bin": "0.108.0",
  "gulp": "4.0.2",
  "gulp-cli": "2.2.0",
  "nodemon": "1.19.2",
  "postcss": "7.0.18",
  "postcss-import": "12.0.1",
  "postcss-loader": "3.0.0",
  "postcss-preset-env": "6.7.0",
  "postcss-url": "8.0.0",
  "style-loader": "1.0.0",
  "webpack": "4.41.0",
  "webpack-cli": "3.3.9",
  "webpack-node-externals": "1.7.2",
  "webpack-manifest-plugin": "2.2.0",
  "webpack-bundle-analyzer": "3.6.0",
  "terser-webpack-plugin": "2.3.5"
};

module.exports = {
  dependencies,
  devDependencies
};
