const dependencies = {
  "@graphql-modules/core": "0.7.15",
  "apollo-cache-inmemory": "1.6.5",
  "apollo-client": "2.6.8",
  "apollo-datasource-rest": "0.8.0",
  "apollo-link-batch-http": "1.2.13",
  "apollo-link-error": "1.1.12",
  "apollo-link-schema": "1.2.4",
  "apollo-link-ws": "1.0.19",
  "apollo-server-express": "2.11.0",
  "commander": "5.0.0",
  "config": "3.3.1",
  "core-js": "3.6.4",
  "express": "4.17.1",
  "express-session": "1.17.0",
  "graphql": "15.0.0",
  "graphql-tools": "4.0.7",
  "isomorphic-fetch": "2.2.1",
  "isomorphic-style-loader": "5.1.0",
  "lodash": "4.17.15",
  "react": "16.13.1",
  "react-apollo": "3.1.4",
  "react-dom": "16.13.1",
  "react-helmet-async": "1.0.4",
  "react-router-dom": "5.1.2",
  "reflect-metadata": "0.1.13",
  "regenerator-runtime": "0.13.5",
  "serve-favicon": "2.5.0"
};

const devDependencies = {
  "@apollo/react-testing": "3.1.4",
  "@babel/cli": "7.8.4",
  "@babel/core": "7.9.0",
  "@babel/plugin-proposal-class-properties": "7.8.3",
  "@babel/plugin-proposal-decorators": "7.8.3",
  "@babel/plugin-proposal-do-expressions": "7.8.3",
  "@babel/plugin-proposal-export-default-from": "7.8.3",
  "@babel/plugin-proposal-export-namespace-from": "7.8.3",
  "@babel/plugin-proposal-function-bind": "7.8.3",
  "@babel/plugin-proposal-function-sent": "7.8.3",
  "@babel/plugin-proposal-json-strings": "7.8.3",
  "@babel/plugin-proposal-logical-assignment-operators": "7.8.3",
  "@babel/plugin-proposal-nullish-coalescing-operator": "7.8.3",
  "@babel/plugin-proposal-numeric-separator": "7.8.3",
  "@babel/plugin-proposal-optional-chaining": "7.9.0",
  "@babel/plugin-proposal-pipeline-operator": "7.8.3",
  "@babel/plugin-proposal-throw-expressions": "7.8.3",
  "@babel/plugin-syntax-dynamic-import": "7.8.3",
  "@babel/plugin-syntax-import-meta": "7.8.3",
  "@babel/plugin-transform-async-to-generator": "^7.8.3",
  "@babel/plugin-transform-regenerator": "7.8.7",
  "@babel/preset-env": "7.9.0",
  "@babel/preset-flow": "7.9.0",
  "@babel/preset-react": "7.9.4",
  "@testing-library/jest-dom": "5.3.0",
  "@testing-library/react": "10.0.2",
  "babel-loader": "8.1.0",
  "babel-plugin-dynamic-import-node": "2.3.0",
  "babel-plugin-transform-require-ignore": "0.1.1",
  "css-loader": "3.4.2",
  "flow-bin": "0.122.0",
  "gulp": "4.0.2",
  "gulp-cli": "2.2.0",
  "identity-obj-proxy": "3.0.0",
  "jest": "25.2.7",
  "nodemon": "2.0.2",
  "postcss": "7.0.27",
  "postcss-import": "12.0.1",
  "postcss-loader": "3.0.0",
  "postcss-preset-env": "6.7.0",
  "postcss-url": "8.0.0",
  "style-loader": "1.1.3",
  "terser-webpack-plugin": "2.3.5",
  "webpack": "4.42.1",
  "webpack-bundle-analyzer": "3.6.1",
  "webpack-cli": "3.3.11",
  "webpack-manifest-plugin": "2.2.0",
  "webpack-node-externals": "1.7.2"
};

module.exports = {
  dependencies,
  devDependencies
};
